In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset = load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame(dataset.data, columns=dataset.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [8]:
df['target'] = dataset.target

In [9]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
df['target'].unique()

array([0, 1, 2])

In [11]:
df_copy = df[df['target']!=2]

In [12]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [13]:
df_copy['target'].unique()

array([0, 1])

In [14]:
# independent and dependent features
X = df_copy.iloc[:, :-1]
y = df_copy.iloc[:, -1]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [17]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((80, 4), (80,), (20, 4), (20,))

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
classification=LogisticRegression(max_iter=200)

In [20]:
classification.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [21]:
y_pred = classification.predict(X_test)

In [22]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion metrics, Accuracy, Classification Report

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [24]:
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [25]:
print(accuracy_score(y_test, y_pred))

1.0


In [26]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## cross validation

In [27]:
from sklearn.model_selection import KFold

In [28]:
cv = KFold(n_splits=5)

In [29]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [30]:
# cross val score
from sklearn.model_selection import cross_val_score

In [31]:
score = cross_val_score(classification,X_train,y_train,scoring='accuracy', cv=cv)

In [32]:
np.mean(score)

1.0

In [33]:
# lets create the complex data

from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [34]:
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant =5, n_classes=2, random_state=1)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

In [37]:
complex_model = LogisticRegression(max_iter=200)

In [38]:
complex_model

LogisticRegression(max_iter=200)

In [39]:
complex_model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [40]:
y_pred_complex = complex_model.predict(X_test)

In [41]:
print(confusion_matrix(y_test, y_pred_complex))

[[78 13]
 [29 80]]


In [42]:
print(accuracy_score(y_test, y_pred_complex))

0.79


In [43]:
print(classification_report(y_test,y_pred_complex))

              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [44]:
# cross validation
cv = KFold(n_splits=5, shuffle=True)
score = cross_val_score(complex_model, X_train, y_train, cv=cv)

In [45]:
score

array([0.76875, 0.81875, 0.85   , 0.79375, 0.825  ])

In [46]:
np.mean(score)

0.81125